name: Exemplo de GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Solicitar entrada do usuário
        run: |
          echo "Insira o valor de FOO:"
          read FOO
          echo "Insira o valor de BAR:"
          read BAR

      - name: Exibir variáveis de ambiente
        env:
          FOO: ${{ env.FOO }}
          BAR: ${{ env.BAR }}
        run: |
          echo "Valor de FOO: $FOO"
          echo "Valor de BAR: $BAR"
