name: User input example

on: [push]

jobs:
  user-input:
    runs-on: ubuntu-latest
    steps:
      - name: Request user input
        id: vars
        run: |
          echo "Enter value for FOO"
          read foo
          echo "Enter value for BAR"
          read bar
          echo "::set-output name=foo::$foo"
          echo "::set-output name=bar::$bar"
      - name: Print variables
        run: |
          echo "FOO = ${{ steps.vars.outputs.foo }}"
          echo "BAR = ${{ steps.vars.outputs.bar }}"
