name: Exemplo de leitura de Secrets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Ler variável de Secrets
        env:
          TESTE: ${{ env.TESTE }}
        run: echo $TESTE
